export const linksByRole = {
  admin: [
    { label: 'Dashboard', path: '/admin/dashboard' },
    { label: 'Reports', path: '/admin/reports' },
    { label: 'Product Requests', path: '/admin/product-requests' },
    { label: 'Inspector Visits', path: '/admin/inspector-visits' },
    { label: 'History', path: '/admin/history' },
    { label: 'Stations', path: '/stations' },
    { label: 'Reconciliation', path: '/reconciliation' },
    { label: 'Alerts', path: '/alerts' },
    { label: 'Analytics', path: '/analytics' },
    { label: 'Users', path: '/users' },
    { label: 'Settings', path: '/settings' },
  ],
  supervisor: [
    { label: 'Dashboard', path: '/supervisor' },
    { label: 'Visitation Report', path: '/supervisor?view=inspector-visits' },
    { label: 'History', path: '/supervisor?view=history' },
    { label: 'Stations', path: '/stations' },
    { label: 'Reconciliation', path: '/reconciliation' },
    { label: 'Alerts', path: '/alerts' },
    { label: 'Analytics', path: '/analytics' },
    { label: 'Users', path: '/users' },
    { label: 'Settings', path: '/settings' },
  ],
  terminal_operator: [
    { label: 'Dashboard', path: '/terminal-operator' },
    { label: 'Station Requests', path: '/terminal-operator?view=requests' },
    { label: 'Direct Dispatch', path: '/terminal-operator?view=direct' },
    { label: 'Dispatch History', path: '/terminal-operator?view=history' },
    { label: 'Costing', path: '/terminal-operator?view=costing' },
    { label: 'Terminal Stock', path: '/terminal-operator?view=stock' },
    { label: 'Reports', path: '/terminal-operator?view=reports' },
    { label: 'Settings', path: '/settings' },
  ],
  inspector: [
    { label: 'New report', path: '/inspector' },
    { label: 'History', path: '/inspector?view=history' },
    { label: 'Settings', path: '/settings' },
  ],
  staff: [{ label: 'Manager Dashboard', path: '/staff' }],
}
